### ISSUE TITLE
Update documentation related to external accounts and publishing

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/wt-design-docs#111]
Account for changes for v0.9 including;
* User settings/external accounts
* Publishing (Publishing Guide)

**Comment by ThomasThelen** [comment]
A new documentation page was created for the settings page in [this](https://github.com/whole-tale/wt-design-docs/commit/ce2ad874978ddeb2090bf911766fb551ed576c18) commit

The publishing docs were updated to include Zenodo in [this](https://github.com/whole-tale/wt-design-docs/commit/e1758bea1d8e570355b3b276e1b3efbde6ebd2f1) one
