### ISSUE TITLE
Module error when trying example new tale

### ISSUE THREAD

**Issue by mohammad-akhlaghi** [whole-tale/wt-design-docs#113]
Dear Whole Tale documentation team,

I was trying out the [Creating a new tale](https://wholetale.readthedocs.io/en/stable/users_guide/quickstart.html#quickstart-composing) part of the documentation, but came with the following error when trying the [provided Jupyter notebook](https://wholetale.readthedocs.io/en/stable/_downloads/e3502f659388bf877f61a939b53d4757/wt_quickstart.ipynb).

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-293c0e2e1c09> in <module>
----> 1 from bokeh.io import show, output_notebook
      2 from bokeh.models import (
      3     ColumnDataSource,
      4     HoverTool,
      5     LogColorMapper

ModuleNotFoundError: No module named 'bokeh'
```

**Comment by ThomasThelen** [comment]
I can also confirm this behavior. @craig-willis do you think this warrants installing bokeh on the python environments? We could alternatively provide a different example notebook

**Comment by craig-willis** [comment]
@ThomasThelen the Quickstart doc was not updated to account for the move to `repo2docker`.  The example needs a `requirements.txt` and `postBuild`.

`requirements.txt`:
```
bokeh
pandas
```

`postBuild`:
```
#!/bin/bash
bokeh sampledata
```
