### ISSUE TITLE
Add documentation for "asTale" parameter

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/wt-design-docs#116]
The mockups for https://github.com/whole-tale/dashboard/issues/579 include the "Why would I do this" link that should point to documentation answering the question.

**Comment by ThomasThelen** [comment]
Note to remind myself to include this in the test document

**Comment by ThomasThelen** [comment]
This is in the latest user documents (not deployed yet but in master) in the Compose page, under `Choosing Between Read only and Read/Write`
