### ISSUE TITLE
Update user guide for new features

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/wt-design-docs#144]
For the upcoming release, we need to write user documentation for:
* [x] Git integration
* [x] Sharing
* [x] Versioning
* [x] MATLAB and Stata

Also update sections that are out of date:
* [x] Features and limitations
* [x] Usage scenarios (add Git/sharing/versioning concepts)
* [x] Sign-in (new screenshot)
* [x] Browse (new screenshots, Public/My Tales)
* [x] Environments (horribly out of date -- maybe drop and leave on create?, launch = run)

**Comment by ThomasThelen** [comment]
I'm fine with axing the 'Environments' section if it's too much to maintain; listing the contents of each environment isn't exactly a scalable solution for future additions. As mentioned, we do list the provided environments with less detail under the `Provided Environments` section on the 'compose' page.
