### ISSUE TITLE
Add Terms of Service page

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/wt-design-docs#147]
The Login page points to the docs link, `https://docs.wholetale.org/tos` for the Terms of Service. We should add that page to the readthedocs.

**Comment by craig-willis** [comment]
It's been merged just not to stable

https://wholetale.readthedocs.io/en/latest/tos/

**Comment by ThomasThelen** [comment]
Oops completely blanked that this wouldn't be on production yet.
