### ISSUE TITLE
Content of Login Page (three columns)

### ISSUE THREAD

**Issue by Xarthisius** [whole-tale/wt-design-docs#15]

**Comment by Xarthisius** [comment]
For reference

![mockup](https://github.com/whole-tale/wt-design-docs/raw/master/mockups/wt-01-login.png)

**Comment by ludaesch** [comment]
Compute: ⇒ analyze your data, run a notebook 
Collaborate: ⇒ share and collaborate on notebooks
Reproduce: ⇒  explore and interact with published research

**Comment by ian-taylor** [comment]
Added
