### ISSUE TITLE
Deploy v1.0

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/wt-design-docs#158]
Deployment steps:
* [x] Tag v1.0
* [x] Wait for Dockerhub to rebuild images
* [x] Backup prod database
* [x] Maintenance mode
* [x] Update traefik config for v2 (traefik.toml, vocab.toml, migrate acme.json)
* [x] Update swarm stack compose 
* [x] Configure experimental flag on Docker on all nodes; restart Docker
* [x] Copy licenses
* [x] Update start-worker.sh (matlab key, licenses), restart workers
* [x] Deploy stata-install images
* [x] Deploy matlab-install images
* [x] Run migration script and manual steps
* [x] Manually trigger image cache rebuild
* [x] Smoke test
* [x] Remove maintenance mode

**Comment by matthewturk** [comment]
Congratulations!!!!!
