### ISSUE TITLE
how to best link to whole tail from my git repo

### ISSUE THREAD

**Issue by jmccreight** [whole-tale/wt-design-docs#178]
I dont see a "best way to link" to my tale from my git repo (that is the tale).
E.g. as binder provides when you put in a https://mybinder.org/
I can use the tale URL, but there's no fancy badge svg file for the link! 

I'm sure other's will want a flashy way to connect their git repo to their tale too. thanks for your tips.

**Comment by jmccreight** [comment]
maybe the link from repo to tale is misleading because the tale dosent automatically track the repo? is that a reason not to promote whole tale on repos?

**Comment by Xarthisius** [comment]
Do you mean like here: https://github.com/whole-tale/julia-example/tree/master ?

**Comment by jmccreight** [comment]
Ooooh! Fancy. I love them. I did scour the user's guide and did not see them. It'd be good to have them in there visually. Thank you.
