### ISSUE TITLE
Making the filesystem structure conducive to constructing new tales

### ISSUE THREAD

**Issue by matthewturk** [whole-tale/wt-design-docs#22]
As per discussion at the all-hands, what we've sort of settled on is to have three directories (see [related dashboard issue](https://github.com/whole-tale/dashboard/issues/44)) that are accessible.

 * `/data/`
 * `~/staging/`
 * `~/`

The first (`/data/`, which may or may not have a symlink in the home directory) will be the virtual filesystem, composed of the data collection or collections selected in construction of the tale or research environment.

The second will be a "readymade" place to put new items that will be, in itself, a new collection.  The workflow here is that you can do work in your home directory, and curate manually items to place into this collection.  When the instance is stopped, this staging area will become a "ready-made" collection for a new Tale.  (We may want to make a "stop and make into a tale" button on the instance management page.)  This is not shared across instances.

The final will be the home directory, which will be synchronous and shared across instances.

**Comment by MatthewTurk** [comment]
If I've misremembered our discussion, please correct @nigaffney @kylechard @Xarthisius @ian-taylor

**Comment by MatthewTurk** [comment]
We've decided to change `staging` to `workspace`

**Comment by MatthewTurk** [comment]
After discussion with @kylechard and @Xarthisius what we've decided upon is that `workspace` will be mutable and affiliated with the Tale.  The `workspace` will be copied when it becomes "mutable" and someone else runs a tale.

WT won't make an actual copy unless a new Tale is actually created.

This solves:

 * Name Collisions
 * Pathnames (relative and absolute)
 * Allowing people to modify existing Tales

**Comment by Xarthisius** [comment]
I'd say: WT won't make an actual copy unless a new Tale is **saved by the author**

**Comment by Xarthisius** [comment]
The `workspace` will be copied when it becomes **"immutable"**

**Comment by MatthewTurk** [comment]
Some more discussion included that the "workspace" directory would also be where you started.

**Comment by Xarthisius** [comment]
I think it's roughly implemented right now (`data`, `workspace`, `home`). Please reopen if we missed something.
