### ISSUE TITLE
Service orchestration

### ISSUE THREAD

**Issue by MatthewTurk** [whole-tale/wt-design-docs#3]
The mechanism by which services are spun up, managed, and interacted with (@ian-taylor and @Xarthisius )

**Comment by Xarthisius** [comment]
Currently I'm using:
 * [Terraform](https://www.terraform.io/) for infrastructure management (it's possible at NCSA, TACC doesn't allow for external API access to their cloud)
 * [Docker compose](https://docs.docker.com/compose/) for service management on a single node.

We should probably look into what NDS Labs offers.

**Comment by mbjones** [comment]
I've recently been looking at the [Carina](https://getcarina.com/) container environment, which is in public beta by Rackspace.  From a UI/deployment perspective its really pretty easy, and we might think of it for our Dashboard UI for configuring compute.  The web UI sets up a single button ability to create docker swarm that you personally can access with normal docker and docker-compose tools, and then can be scaled easily.  Any containers launched into the swarm are automatically deployed on nodes in the swarm, and it has a reasonable balancing algorithm.  Scaling up the cluster is a simple matter of adding nodes to the swarm via a dropdown.  See screen shot:

<img width="930" alt="screen shot 2016-09-02 at 1 35 07 pm" src="https://cloud.githubusercontent.com/assets/766407/18218966/8c7eccf8-7112-11e6-9926-56c98d80f67c.png">

In addition, I think looking at systems like [Kubernetes](http://kubernetes.io/) or [Apache Mesos](http://mesos.apache.org/) is worthwhile, unless NDS is already providing something similar.

**Comment by Xarthisius** [comment]
NDS Labs is based on Kubernetes. Having said that I'd love to try Carina (or [Magnum](https://wiki.openstack.org/wiki/Magnum) in general) for native docker support on OpenStack. I also think that [Murano](https://wiki.openstack.org/wiki/Murano) would go naturally with it and possible solve #2 

However, we are still waiting for our OpenStack admins to get those installed, again I have no ETA.

**Comment by Xarthisius** [comment]
https://github.com/whole-tale/terraform_deployment
