### ISSUE TITLE
Document Running and Managing Tales

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/wt-design-docs#37]
Update User Guide to include description of how a user runs and manages running tales including deletion.

**Comment by ThomasThelen** [comment]
I think this has been covered now.

Tale deletion can be found under
http://wholetale.readthedocs.io/users_guide/browse.html#delete-a-tale

Running and Managing can be found under
http://wholetale.readthedocs.io/users_guide/browse.html
http://wholetale.readthedocs.io/users_guide/run.html#interacting-with-tales
