### ISSUE TITLE
Document Importing  (registering) data into WT

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/wt-design-docs#38]
Update User Guide to include description of how/why user would import/register data into WT and how this relates to Tales creation/publishing.

**Comment by ThomasThelen** [comment]
This has been documented under 
http://wholetale.readthedocs.io/users_guide/manage.html

It includes instructions and pictures on how to register data from Globus & DataONE

**Comment by ThomasThelen** [comment]
These changes have since been merged. Closing
