### ISSUE TITLE
Add documentation describing Dataverse integration

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/wt-design-docs#61]
* Describe basics of Dataverse support (registration/import)
* Describe future (APJS-style tale import and execution)
* How to add WT as external tool + our official external tools json
  * Note Girder host/domain for alternative installations
* PR to Dataverse documentation
  * https://github.com/IQSS/dataverse/issues/5097#issuecomment-440404718

From Slack
>  Think of it more as “In our docs, make it so you can download a JSON file”. It could just be a link in a README. For an example please see “Data Explorer” at http://guides.dataverse.org/en/4.9.4/installation/external-tools.html#inventory-of-external-tools

**Comment by Xarthisius** [comment]
This should also include manifest for our external tool integration:

```
{
  "displayName": "Whole Tale",
  "description": "Analyze in Whole Tale",
  "type": "explore",
  "toolUrl": "https://girder.prod.wholetale.org/api/v1/integration/dataverse",
  "toolParameters": {
    "queryParameters": [
      {
        "fileId": "{fileId}"
      },
      {
        "siteUrl": "{siteUrl}"
      },
      {
        "key": "{apiToken}"
      }
    ]
  }
}
```

**Comment by pdurbin** [comment]
> This should also include manifest for our external tool integration

Yes! This would unblock https://github.com/IQSS/dataverse/issues/5097 as long as you also include some instructions on how to load up the manifest in Dataverse. Thanks!

**Comment by craig-willis** [comment]
Reopening until we have a PR for the Dataverse docs.  Work is mostly done, pending our deployment: https://github.com/IQSS/dataverse/compare/develop...craig-willis:5097-wholetale-integration

**Comment by pdurbin** [comment]
@craig-willis I'm happy to answer any questions you have on building the Dataverse docs. Mostly it's:

`cd doc/sphinx-guides`

`make html`

**Comment by craig-willis** [comment]
Thanks, @pdurbin. The build works for me without problem. We've just decided not to submit the PR until our release is finished.

**Comment by pdurbin** [comment]
@craig-willis that makes sense. Thanks.

**Comment by craig-willis** [comment]
https://wholetale.readthedocs.io/en/stable/users_guide/integration.html?highlight=dataverse
