### ISSUE TITLE
Developer documentation for "Analyze in WT" feature

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/wt-design-docs#62]
This documentation should be targeted at someone who is using one of our existing  supported data providers (DataONE member, someone with data exposed via HTTP, Globus, etc) and wants to add "Analyze in WT" to their site:
* Document that dashboard has this functionality (e.g., uri, name, environment...)
* Include documentation for writing a custom integration (e.g., dataverse)

**Comment by ThomasThelen** [comment]
Done in PR #88
