### ISSUE TITLE
avoiding {"status":"ERROR","message":"scope is required."} for versions of Dataverse newer than 4.16

### ISSUE THREAD

**Issue by pdurbin** [whole-tale/wt-design-docs#95]
Hello! Please be advised that the next version of Dataverse (after 4.16) will require a "scope" of "file" for your manifest file to be loaded into Dataverse. In my testing of other tools, I've been putting "scope" right above "type", like this:

    "scope": "file",
    "type": "explore",

You don't need to worry about backward compatibility. Dataverse 4.16 and below will happily accept "scope". What we are trying to avoid is {"status":"ERROR","message":"scope is required."} on newer versions of Dataverse.

It looks like the manifest was last edited in a5df111.

#61 seems to be related.

**Comment by Xarthisius** [comment]
@pdurbin Out of curiosity: why are you breaking every external tool manifest that's out there by requiring `"scope"` keyword? Wouldn't it make more sense to default to `"scope": "file"` if `scope` is not present?

**Comment by pdurbin** [comment]
@Xarthisius good question! We didn't consider this. Our thinking (or non-thinking) is probably influenced by the fact that there are only five Dataverse external tools in the world. Sorry for the inconvenience! If you feel strongly that we should change the code on the Dataverse side, please feel free to open an issue at https://github.com/IQSS/dataverse/issues

I'm happy to make a pull request to to this repo if you want. Again, it should only be a one line change. I was thinking Whole Tale might want to use a scope of "dataset" and be the first dataset tool! What do you think? 😄 Or you could offer manifests for both the file and the dataset level. It's totally up to you, of course. 😄

**Comment by Xarthisius** [comment]
> @Xarthisius good question! We didn't consider this. Our thinking (or non-thinking) is probably influenced by the fact that there are only five Dataverse external tools in the world. 
Five that you know of ;-)

I'm fine with changing it on our end, as we actually much prefer "dataset" scope.

**Comment by pdurbin** [comment]
@Xarthisius sounds good. If you want to update the list below to change Whole Tale from "file" to "dataset" (the first!) the file to edit is https://github.com/IQSS/dataverse/blob/develop/doc/sphinx-guides/source/_static/admin/dataverse-external-tools.tsv

![Screen Shot 2019-09-23 at 3 37 42 PM](https://user-images.githubusercontent.com/21006/65456846-3b7add80-de18-11e9-9b96-b4ac2b2809c5.png)
