### ISSUE TITLE
Create Tale and Launch in tale modal behaves poorly

### ISSUE THREAD

**Issue by hategan** [whole-tale/wt-design-docs#99]
Steps to reproduce:
1. Browse > Create New... > Create New Tale
2. Enter details
3. Click on "Create tale and launch"

There is no feedback to the user that the button was clicked until the server processes the relevant request. The user can click repeatedly on the "Create tale and launch" button, each click triggering a new request, which creates a new tale. Presumably when the server acknowledges the first request, the modal disappears, but multiple tales are created.

**Comment by ThomasThelen** [comment]
Filed in the dashboard
